apiVersion: v1
kind: Service
metadata:
  name: gradle-example-service
  labels:
    app: gradle-example-deployment
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: gradle-example-deployment
  type: LoadBalancer
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: gradle-example-deployment
spec:
  selector:
    matchLabels:
      app: gradle-example-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: gradle-example-deployment
    spec:
      containers:
      - name: master
        image: sepasoporteit/ejemplo
        ports:
        - containerPort: 8080